### PR TITLE
fix: add total count to header

### PR DESCRIPTION
**Pull request by Sekir0**

### CODE REVIEW

**Review by volodymyr-borodin — DISMISSED** [review]

**Comment by volodymyr-borodin** [comment]
@Sekir0 test code coverage lower that minimum value, please increase it up to 60%

**Comment by volodymyr-borodin** [comment]
@Sekir0 what's the reason for this functionality?

Messages and chats list should be displayed in infinite scroll manner, for this reason you don't need total count
Infinite scroll approach in our solution next:
- first request without cursor
- if amount of requested items equals amount of returned values -> request next portion with cursor parameter
- otherwise this is end of elements

see example in news feed: https://github.com/ghosts-network/web-spa/blob/master/src/app/pages/home/home.page.ts#L52

If the are other reasons let me know. Otherwise PR will be closed in 7 days

**Comment by Sekir0** [comment]
kk

**Comment by volodymyr-borodin** [comment]
@Sekir0 however could you please rise separate PR with new unit tests?

**Comment by Sekir0** [comment]
Yup

**Pull request closed without merging**
